version: '3.7'
services:
  node:
    build: .
    networks:
      - net
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    depends_on:
      - database
    environment:
      - PORT=${PORT}

  database:
    build: ./database
    networks:
      - net
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  net: