version: '3'
services:
  node:
    build: .
    networks:
      - my-net
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    environment:
      - PORT=${PORT}

  database:
    build: ./database
    networks:
      - my-net
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  my-net: